export const LABELS = {
  SESSION_NOT_FOUND: "SESSION NOT FOUND",
  BACK_TO_EVENTS: "Back to events",
  NO_SESSIONS: "No sessions on this day",
  NO_EVENTS: "NO EVENTS FOUND",
  ADJUST_FILTERS: "Try adjusting your filters",
  CLEAR_FILTERS: "Clear all filters",
  SESSION_CONCLUDED: "Session Concluded",
  BROADCAST_ENDED: "The live broadcast has ended.",
  UPCOMING_SESSION: "Upcoming Session",
  QUESTIONS_NOT_OPEN: "Questions Not Open Yet",
  QUESTIONS_LOCKED: "Questions will unlock when this session is live.",
  SESSION_ENDED: "Session Ended",
  NO_QUESTIONS: "No questions were asked.",
  NO_QUESTIONS_YET: "No Questions Yet",
  ASK_QUESTIONS: "Stream is active — ask your questions below!",
  UPCOMING: "UPCOMING",
  LIVE: "LIVE",
  ENDED: "ENDED",
  ONLINE: "ONLINE",
  ONSITE: "ONSITE",
  ALL_DAYS: "All Days",
  WATCH_LIVE: "WATCH LIVE",
  NOT_YET_LIVE: "NOT YET LIVE",
  VIEW_DETAILS: "VIEW FULL DETAILS",
} as const;
